Dataset Description: It contains a total of 17 columns. Letâ€™s take a look at them.

Attribute Information :

1. id
2. city
3. date
4. player_of_match
5. venue
6. neutral_venue
7. team1
8. team2
9. toss_winner
10. toss_decision
11. winner
12. result
13. result_margin
14. eliminator
15. method
16. umpire1
17. umpire2

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
# Read the dataset
df = pd.read_csv("./data/ipl/IPL Matches 2008-2020.csv")

In [6]:
df.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [7]:
# Remove useless columns
df.drop(labels = ['id', 'date', 'player_of_match', 'neutral_venue', 'result', 'result_margin', 'eliminator', 'method','umpire1', 'umpire2'], axis = 1,inplace = True)

In [8]:
df.head()

,city,venue,team1,team2,toss_winner,toss_decision,winner
0,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders
1,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings
2,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils
3,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore
4,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders

In [13]:
match_win_target = match_loss_target = match_win_chassing = match_loss_chassing = 0 
for i in range(len(df)) : 
    if df.toss_decision.iloc[i] == 'bat' :    # target diya
        if df.toss_winner.iloc[i] == df.winner.iloc[i] : 
            match_win_target += 1
        else :
            match_loss_target += 1
    else :          # target chase kiya or Fielding li
        if df.toss_winner.iloc[i] == df.winner.iloc[i] : 
            match_win_chassing += 1
        else :
            match_loss_chassing += 1
print('{} times captain choose batting option and win the match.'.format(match_win_target))
print('{} times captain choose batting option but loose the match.'.format(match_loss_target))
print('{} times captain choose fielding option and win the match.'.format(match_win_chassing))
print('{} times captain choose fielding option but loose the match.'.format(match_loss_chassing))

145 times captain choose batting option and win the match.
175 times captain choose batting option but loose the match.
273 times captain choose fielding option and win the match.
223 times captain choose fielding option but loose the match.

In [37]:
# create a dummy column for target and chase
df["target"] = np.nan
df["chase"] = np.nan
df['venue1'] = np.nan

In [38]:
df.head()

,city,venue,team1,team2,toss_winner,toss_decision,winner,target,chase,venue1
0,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,NaN,NaN,NaN
1,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,NaN,NaN,NaN
2,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,NaN,NaN,NaN
3,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,NaN,NaN,NaN
4,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,NaN,NaN,NaN

In [39]:
#  how the team wins the match - either by setting target score/ chasing the score
for i in range(len(df)) : 
    if df.toss_decision.iloc[i] == 'bat' :    
        if df.toss_winner.iloc[i] == df.winner.iloc[i] : 
            # captain choose batting option and win the match then it will count as target.
            df['target'].iloc[i] = 1       
        else :
            # captain choose batting option and loose the match then it will count as chasing.
            df['chase'].iloc[i] = 1   
    else :          
        if df.toss_winner.iloc[i] == df.winner.iloc[i] : 
            # captain choose fielding option and win the match then it will count in chasing.
            df['chase'].iloc[i] = 1   
        else :
            # captain choose fielding option and loose the match then it will count in target.
            df['target'].iloc[i] = 1

/tmp/ipykernel_21339/347627788.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'].iloc[i] = 1
/tmp/ipykernel_21339/347627788.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'].iloc[i] = 1
/tmp/ipykernel_21339/347627788.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['chase'].iloc[i] = 1
/tmp/ipykernel_21339/347627788.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['chase'].iloc[i] = 1

In [40]:
top15_stadium = ['Eden Gardens, Kolkata', 'Feroz Shah Kotla, Delhi', 'Wankhede Stadium, Mumbai',
                    'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
                    'M Chinnaswamy Stadium, Bangalore',
                    'MA Chidambaram Stadium, Chepauk, Chennai',
                    'Sawai Mansingh Stadium, Jaipur', 
                    'Punjab Cricket Association Stadium, Mohali, Chandigarh',
                 'Dubai International Cricket Stadium, Dubai',
                 'Sheikh Zayed Stadium, Abu Dhabi','Maharashtra Cricket Association Stadium, Pune',
                'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh', 'Sharjah Cricket Stadium, Sharjah',
                 'Dr DY Patil Sports Academy, Mumbai', 'Subrata Roy Sahara Stadium, Pune']

In [41]:
targetlist = []
chaselist = []
for i in top15_stadium : 
    print('Analysis on "{} Stadium"'.format(i))
    x = np.sum(df[df.venue1 == i].target)
    y = np.sum(df[df.venue1 == i].chase)
    print(x, 'times team gave good target and win the match.')
    print(y, 'times team easily chase the score and win the match.') 
    targetlist.append(x)
    chaselist.append(y)
    print()

Analysis on "Eden Gardens, Kolkata Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Feroz Shah Kotla, Delhi Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Wankhede Stadium, Mumbai Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Rajiv Gandhi International Stadium, Uppal, Hyderabad Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "M Chinnaswamy Stadium, Bangalore Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "MA Chidambaram Stadium, Chepauk, Chennai Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Sawai Mansingh Stadium, Jaipur Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Punjab Cricket Association Stadium, Mohali, Chandigarh Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Dubai International Cricket Stadium, Dubai Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Sheikh Zayed Stadium, Abu Dhabi Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Maharashtra Cricket Association Stadium, Pune Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Sharjah Cricket Stadium, Sharjah Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Dr DY Patil Sports Academy, Mumbai Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.

Analysis on "Subrata Roy Sahara Stadium, Pune Stadium"
0.0 times team gave good target and win the match.
0.0 times team easily chase the score and win the match.